on: [push, pull_request]
name: Josh5's Awesome server
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: Roang-zero1/factorio-mod-luacheck@master
        with:
          luacheckrc_url: https://raw.githubusercontent.com/MultiCraft/MultiCraft_game/master/.luacheckrc
